import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Flame } from "lucide-react";
const LINKS = [
    { label: "Dashboard", href: "#dashboard" },
    { label: "Forecast", href: "#forecast" },
    { label: "Risk Analysis", href: "#risk-analysis" },
    { label: "Safety", href: "#safety" },
];
export function Footer() {
    return (_jsx("footer", { className: "border-t border-border bg-secondary/30", children: _jsxs("div", { className: "mx-auto w-full max-w-7xl px-4 py-12 sm:px-6", children: [_jsxs("div", { className: "grid gap-8 sm:grid-cols-2 lg:grid-cols-3", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("span", { className: "flex size-10 items-center justify-center rounded-xl deep-panel shadow-sm", children: _jsx(Flame, { className: "size-5" }) }), _jsxs("span", { className: "leading-tight", children: [_jsx("span", { className: "block font-display text-lg font-semibold tracking-tight", children: "HeatGuard" }), _jsx("span", { className: "block text-[11px] font-medium uppercase tracking-[0.16em] text-muted-foreground", children: "Heat-Stress Intelligence" })] })] }), _jsx("p", { className: "mt-4 max-w-sm text-sm leading-relaxed text-muted-foreground", children: "AI-Powered Heat-Stress Risk Assessment System." })] }), _jsxs("div", { children: [_jsx("h4", { className: "font-display text-sm font-semibold uppercase tracking-wide text-muted-foreground", children: "Navigation" }), _jsx("ul", { className: "mt-4 space-y-2", children: LINKS.map((l) => (_jsx("li", { children: _jsx("a", { href: l.href, className: "text-sm text-muted-foreground transition-colors hover:text-foreground", children: l.label }) }, l.href))) })] }), _jsxs("div", { children: [_jsx("h4", { className: "font-display text-sm font-semibold uppercase tracking-wide text-muted-foreground", children: "Project" }), _jsx("p", { className: "mt-4 text-sm leading-relaxed text-muted-foreground", children: "Powered by React + FastAPI" }), _jsx("p", { className: "mt-2 text-sm leading-relaxed text-muted-foreground", children: "Smart India Hackathon Project" })] })] }), _jsxs("div", { className: "mt-10 border-t border-border pt-6 text-center text-xs text-muted-foreground", children: ["\u00A9 ", new Date().getFullYear(), " HeatGuard. AI-Powered Heat-Stress Risk Assessment System."] })] }) }));
}
